### ISSUE TITLE
Error: MotionVectors

### ISSUE THREAD

**Issue by catafest** [keijiro/KinoMotion#1]
I try to using your code but I got this error:
Assets/Kino/Motion/Motion.cs(160,98): error CS0117: `UnityEngine.DepthTextureMode' does not contain a definition for`MotionVectors'

**Comment by keijiro** [comment]
Motion vectors are only available with the most recent versions of Unity beta (after 5.4.0 b16). Could you verify it with the latest beta (b18)? Please reopen this issue if you find any problem with it.

**Comment by catafest** [comment]
ok, I will test with Unity version 5.4.b019 .
