### ISSUE TITLE
strange encoding and without test demo.

### ISSUE THREAD

**Issue by catafest** [keijiro/KinoMotion#15]
Can you make one demo or readme about how is working ?
- the defaul scene has nothing to test it and also when I try to find some demo scene 
  I got this output over windows 10 **tree** command? The output file is strange is strange encoding ...

```
|   |   +---fc
|   |   +---fd
|   |   +---fe
|   |   \---ff
|   +---ScriptAssemblies
|   \---ShaderCache
|       +---0
|       +---2
|       +---3
|       +---4
|       +---5
|       +---6
|       +---7
|       +---9
|       +---a
|       +---b
|       +---c
|       +---d
|       \---f
+---ProjectSettings
\---Temp
    +---ProcessJobs
    \---__Backupscenes
```

**Comment by keijiro** [comment]
- The unitypackage doesn't include any demo/example. There are some examples in the repository. So, if you need these examples, clone the repository.
- This effect is only supported with Unity 5.4.0 or later. Please make sure that you're using 5.4.
