### ISSUE TITLE
Output is vertically flipped when used with Exr Rec

### ISSUE THREAD

**Issue by keijiro** [keijiro/KinoMotion#16]
Jean Moreno reported this issue.

https://twitter.com/JeanMorenoFr/status/786193945231372288

Note: A minimum repro-project was provided by him.

**Comment by Andreagohsw** [comment]
Hello @keijiro , I am the Technical Supervisor on this project with Jean Moreno (he reported this issue) . Just want to let you know we really love your tool and have been working on the blur with the lighters. 
Is there an estimated time you know that you would look into this? We are on a tight deadline right now and would really love to integrate what you made into our final look. However, if you don't plan to look at this soon, just give us a heads up and we will work around it. Thank you so much for even making this possible! :D

**Comment by jean-moreno** [comment]
Heads up: it looks like turning off frame compression in FrameBlendingFilter prevents the "red image" bug from appearing. Image is still flipped though.

**Comment by keijiro** [comment]
Thanks for providing the information. I looked into the problem and found that it's a little bit hard to solve the problem in a limited time frame. Fortunately, you can easily avoid the problem by adding another image effect between the motion blur and the exporter. For instance, I tried to add my ColorSuite effect between them, and it solved the problem.

![inspector](https://cloud.githubusercontent.com/assets/343936/19995881/a0104bb2-a29e-11e6-9320-ee95df29ff9b.png)

I'll forward this issue to the developer of the exporter.

**Comment by jean-moreno** [comment]
Thanks for the info!
We also found that using a second camera that doesn't render anything, doesn't clear the screen and just holds the Exr Recorder works.
