### ISSUE TITLE
Really messes with default particle system

### ISSUE THREAD

**Issue by teacoat** [keijiro/KinoMotion#18]
The particles get _very_ motion blurry

Example: http://imgur.com/a/gKr0d, The particles are a child of a moving game object, and seem to get very motion blurred at some points depending on the angle of the camera

**Comment by keijiro** [comment]
The motion blur effect only works with opaque materials, so they shouldn't be blurred at all. I guess something weird is happening in that scene.

Would you mind providing a small project that can reproduce the issue? I'd like to look into it.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.
