### ISSUE TITLE
UV Scrolling support ?

### ISSUE THREAD

**Issue by melMass** [keijiro/KinoMotion#22]
Thanks for this.
Is it possible to use KineMotion to alter the motion blur based on UV translation ?

![roadblur](https://user-images.githubusercontent.com/7041726/38323128-af593540-383c-11e8-8930-c27c9c5e4d9d.gif)

**Comment by keijiro** [comment]
It needs motion vectors to process motion. If you write a shader that outputs motion vectors along with UV translation, it will work properly.
