### ISSUE TITLE
windows Visual Studio - update !?

### ISSUE THREAD

**Issue by catafest** [keijiro/KinoMotion#5]
This is common error if I don't used Visual Studio 2015 - update ?
    "Load Failed: unknown solution item type " {E097FAD1-6243-4DAD-9C02-E9B9EFC3FFC1}

**Comment by keijiro** [comment]
I'm pretty sure that this is not relevant to this repository :)

https://www.google.com/search?q=E097FAD1-6243-4DAD-9C02-E9B9EFC3FFC1

If you're confident that this is an issue of KinoMotion, please reopen this ticket. Thanks.

**Comment by catafest** [comment]
**Is fixed after restart the PC**
...by update Windows Visual Studio and Unity ( because come with beta) , because need to use network ... see error:

```
SocketException: An attempt was made to access a socket in a way forbidden by its access permissions.

System.Net.Sockets.Socket.Bind (System.Net.EndPoint local_end)
SyntaxTree.VisualStudio.Unity.Messaging.UdpSocket.Bind (System.Net.IPAddress address, Int32 port)
SyntaxTree.VisualStudio.Unity.Messaging.Messager..ctor (Int32 port)
SyntaxTree.VisualStudio.Unity.Messaging.Messager.BindTo (Int32 port)
SyntaxTree.VisualStudio.Unity.Bridge.VisualStudioIntegration+<>c__DisplayClass3.<.cctor>b__1 ()
SyntaxTree.VisualStudio.Unity.Bridge.Project+<>c__DisplayClass4.<RunOnceOnUpdate>b__3 ()
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorApplicationBindings.gen.cs:218)
```

> you're too fast for me , just trying to understand and make a fair share  of me as a user in the team. and also you come with Editor scripts and unitypackage.

**Comment by keijiro** [comment]
Thanks for the info. Hmm, it seems like an issue of the Visual Studio integration. Sorry I'm not an expert of VS, and have no idea on this error message. Please feel free to reopen if it smells like a problem with KinoMotion 😃
